project:
  type: website
  output-dir: docs

website:
  title: "Gabriel Freider"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: contact.qmd
        text: Contact
      - href: cv.qmd
        text: CV
      - href: Blog.qmd
        text: Blog
      
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

