project:
  type: website
  output-dir: docs

website:
  title: "Quarto Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: cv.qmd
        text: CV
      - href: postsFile.qmd
        text: Blog
        
    right:
      - href: something.qmd or link (https://github.com/FreiderG)
        text: "{{fa stuff}} Thing"
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

